### ISSUE TITLE
Is it possible to have a bundle version of this plugin?

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5-markdown-gfm#15]
Sorry for a maybe silly question, but is there a way to bundle this plugin?

For example if we already have a built version. Do we rebuild classic + gfm?

![image](https://user-images.githubusercontent.com/128755/32529192-1acfbd5a-c405-11e7-9070-de45bc0343f9.png)

**Comment by szymonkups** [comment]
Hi @vladikoff,
To enable markdown data processor you'll need to create a simple plugin as described [here](https://docs.ckeditor.com/ckeditor5/latest/features/markdown.html). Then, you can create your custom build with that plugin as described [here](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html). 

Hope this helps.

**Comment by vladikoff** [comment]
Ah yes that's the page I needed https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html but couldn't find earlier! Thank You!

**Comment by Reinmar** [comment]
> Ah yes that's the page I needed https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html but couldn't find earlier! Thank You!

Out of curiosity, where do you think it should also be mentioned/linked? Did you expect to find such or similar info on some other pages?

I'm asking because I think that it's not visible well enough and I'd like to improve this.

**Comment by vladikoff** [comment]
> Out of curiosity, where do you think it should also be mentioned/linked? Did you expect to find such or similar info on some other pages?

I think I searched for "Ckeditor 5 custom builds" which lead me to https://ckeditor.com/ckeditor-5-builds/ which shows "Classic / Balloon / Inline" but I was hoping to see a way to create a "Custom build" from there

**Comment by Reinmar** [comment]
Thanks! We'll check how we can improve this page.
