### ISSUE TITLE
Cannot get Markdown in ckeditor5-build-decoupled-document

### ISSUE THREAD

**Issue by Donny2333** [ckeditor/ckeditor5-markdown-gfm#22]
```
<div class="document-editor">
    <div class="document-editor__toolbar"></div>
    <div class="document-editor__editable-container">
        <div class="document-editor__editable">
            <h3>The initial editor data.</h3>
            <!-- <figure class="image">
              <img :src="sample" alt="Autumn fields" />
            </figure> -->
        </div>
    </div>
</div>
```

```
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor'
import GFMDataProcessor from '@ckeditor/ckeditor5-markdown-gfm/src/gfmdataprocessor'

function Markdown(editor) {
  editor.data.processor = new GFMDataProcessor()
}

DecoupledEditor.create(
  document.querySelector('.document-editor__editable'),
  {
    toolbar: [],
    plugins: [Markdown]
  }
)
  .then(editor => {
    const toolbarContainer = document.querySelector(
      '.document-editor__toolbar'
    )
    toolbarContainer.appendChild(editor.ui.view.toolbar.element)
    window.editor = editor

    console.log(editor.getData())
  })
  .catch(err => {
    console.error(err)
  })
```

I cannot see any Markdown data in the console. Is any thing wrong wrong??

**Comment by Reinmar** [comment]
You cannot add this plugin to a CKEditor 5 build. You need to either [customize a build](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html) or [build the editor from source](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source).

Let us know if this will help.

**Comment by Reinmar** [comment]
PS. There's a long ticket about how [adding plugins to builds doesn't work](https://github.com/ckeditor/ckeditor5/issues/667).

**Comment by Donny2333** [comment]
I m sorry. I still can not solve this problem...

First, [CKEditor-5's Official Markdown Output Guide](https://docs.ckeditor.com/ckeditor5/latest/features/markdown.html) tells me, I should import @ckeditor/ckeditor5-markdown-gfm to my project and set it into CKEditor's plugins. I followed it, but console throws error:  
`Cannot read property 'getAttribute' of null`

Second, I followed your advice, customizing a build. Even I dont change any code of [ckeditor5-build-decoupled-document](https://github.com/ckeditor/ckeditor5-build-decoupled-document) to build, it still show me importing DecoupledEditor failed: 
`export 'DecoupledEditor' was not found in '@/components/CKEditor/ckeditor'`

I M CONFUSED... 
HELP....
@Reinmar

**Comment by Reinmar** [comment]
You'd need to list what you're doing step by step, so we can repeat that. Right now, I have very blurry idea what you tried to do.

**Comment by Donny2333** [comment]
Finally, I solved this problem...

It turns out to be the case that webpack rules cause it. My project webpack rules conflict with CKEditor5's.

Thanks @Reinmar

**Comment by sirajalam049** [comment]
@Donny2333 

I have the same problem and definitely, it is because of webpack rules conflict. I have created the app using `create-react-app`. Can you please assist how to solve the problem?
